server:
    port: 7002
    
spring:
    profiles: dev
  
    application:
        name: producer-service
    
    message: welcome to location..
        
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:7001/eureka
      
    instance:
        # this is to generate instance id as a unique value
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
    security:
        enabled: false
