server:
  port: 7030
    
spring:
  profiles: dev
  
  application:
    name: product
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7010/eureka
      
  instance:
    # this is to generate instance id as a unique value
    instance-id: ${spring.application.name}:${random.value}